version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - ./build/*
      - ./plugins/*
      - ./shared/go/*/*
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gomod:
        update-types:
          - "patch"
  - package-ecosystem: cargo
    directories:
      - /plugins/*
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      cargo:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"
