repos:
  - repo: local
    hooks:
      - id: rust-fmt
        name: rust-fmt
        description: Format files with rustfmt.
        entry: rustfmt +nightly --color always
        types: [rust]
        language: system
        stages: [pre-commit]
      - id: dco
        name: dco
        entry: ./tools/local_hooks/dco-pre-commit-msg.sh
        language: script
        stages: [prepare-commit-msg]
