repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v18.1.3'
    hooks:
    - id: clang-format
      name: clang-format-18
      files: ^plugins/container/.*$
      exclude: plugin_config_schema\.h
      stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.6'
    hooks:
    - id: clang-format
      name: clang-format-14
      files: ^plugins/(k8smeta|dummy_c)/.*$
      stages: [pre-commit]
  - repo: local
    hooks:
      - id: rust-fmt
        name: rust-fmt
        description: Format files with rustfmt.
        entry: rustfmt +nightly --color always
        types: [rust]
        language: system
        stages: [pre-commit]
      - id: dco
        name: dco
        entry: ./tools/local_hooks/dco-pre-commit-msg.sh
        language: script
        stages: [prepare-commit-msg]
