# This is a reusable workflow used by main and release CI
on:
  workflow_call:
    inputs:
      output:
        description: Name of the output binary
        required: false
        default: rules-check
        type: string
      repository:
        description: Falco rules repository
        required: false
        default: falcosecurity/rules
        type: string

jobs:
  build-rules-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26'

      - name: Checkout rules
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ inputs.repository }}

      - name: Build checker tool
        working-directory: build/checker
        run: go build -o ${{ inputs.output }}

      - name: Test checker tool
        working-directory: build/checker
        run: go test ./... -cover

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rules-tool.tar.gz
          path: build/checker/${{ inputs.output }}
          retention-days: 1
